# Generated by Django 6.0.7 on 2026-09-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
