# Generated by Django 6.0.7 on 2026-09-22 17:49

import django.core.validators
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='products/manuals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), products.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
    ]
